# Python DevContainer
FROM mcr.microsoft.com/devcontainers/python:3.11

# Install any OS dependencies you need here
# RUN apt-get update && apt-get install -y <your-package-list>

# Set the working directory
WORKDIR /workspaces/hungaromet

# (Optional) Install Python dependencies here, but devcontainer.json will handle requirements.txt
# COPY requirements.txt ./
# RUN pip install -r requirements.txt
